apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
        - image: bitnami/kubectl:latest
          imagePullPolicy: Always
          name: kube
          command: ["version"]

