apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - image: diegotc/guestbook:7f0d7a0d4c6901d9e2f832577eaa6a0b4622cc68
          imagePullPolicy: Always
          name: chat-ui
          ports:
            - containerPort: 5000