apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - image: diegotc/guestbook:0ee02389bd2e621838fe2db03b4210ae48f612c7
          imagePullPolicy: Always
          name: chat-ui
          ports:
            - containerPort: 5000