apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - image: diegotc/guestbook:b925fc5d1fd6390276805b98eff07a4a6f8f652f
          imagePullPolicy: Always
          name: chat-ui
          ports:
            - containerPort: 5000