apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - image: diegotc/guestbook:9c52d5b6931b1392d2c2ad2e13ee41992dde195e
          imagePullPolicy: Always
          name: chat-ui
          ports:
            - containerPort: 5000