apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - image: diegotc/guestbook:20230621-051440
          imagePullPolicy: Always
          name: chat-ui
          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15

          startupProbe:
            httpGet:
              path: /status
              port: 5000
            failureThreshold: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10