apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl-v2
  namespace: argocd
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: internal-kubectl
      image: alpine/k8s:1.27.4
      command: [ "sh", "-c" ]
      args:
        - >
          kubectl get pods