apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: internal-kubectl
      image: alpine/k8s
      command: [ "sh", "-c" ]
      args:
        - >
          kubectl get pods