name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{secrets.DOCKER_USER}}/guestbook
        tags: |
          type=raw,value={{date 'YYYYMMDD-hhmmss'}}
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        tags: ${{ steps.meta.outputs.tags }}
        push: true
#    - name: Replace image
#      run: |
#        ls -lah
#        pwd
#        new_ver=$GITHUB_SHA
#        echo $new_ver
#        cd argo
#        ls -lah
#        sed -i -e "s/diegotc\/guestbook:.*/diegotc\/guestbook:$new_ver/g" deployment.yaml
    - name: Replace image
      run: |
        ls -lah
        pwd
        new_ver= echo ${{ steps.meta.outputs.tags }} | sed 's/^.*://g'
        echo "Opcion1"
        cd argo
        ls -lah
        echo $new_ver
        sed -i -e "s/diegotc\/guestbook:.*/diegotc\/guestbook:$new_ver/g" deployment.yaml
        echo "Opcion 2" + $new_ver
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Replace image
#      run: |
#        new_var= echo ${{ steps.meta.outputs.tags }} | sed 's/^.*://g'
#        echo $new_var
#        cd argo
#        sed -i -e 's/diegotc\/guestbook:.*/diegotc\/guestbook:$new_var/g' deployment.yaml
#    - name: Commit & Push changes
#      uses: actions-js/push@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}