name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile  --tag ${{secrets.DOCKER_USER}}/guestbook:$GITHUB_SHA
    - name: Push the image
      run: docker push ${{secrets.DOCKER_USER}}/guestbook --all-tags
    - name: 🏗 Set up yq
      uses: frenck/action-setup-yq@v1
    - name: Print
      run: echo $GITHUB_SHA
    - name: Create tmp folder
      run: |
        tmp_dir=$(mktemp -d)
        echo $tmp_dir
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        path: $tmp_dir
    - name: Replace image
      run: sed -i '' -e "s/diegotc\/guestbook:.*/diegotc\/guestbook:$GITHUB_SHA/g" $tmp_dir/argo/deployment.yaml
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}