name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Tagging
      uses: HackerHappyHour/tagging-strategy@v3
      with:
        tag_name: '1.0.0'
        tags: '%X%'
        image_name: ${{secrets.DOCKER_USER}}/guestbook
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        tags: ${{ steps.tagging-strategy.outputs.tags }}
        push: true
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile  --tag ${{secrets.DOCKER_USER}}/guestbook:$GITHUB_SHA
#    - name: Push the image
#      run: docker push ${{secrets.DOCKER_USER}}/guestbook --all-tags
#    - name: Print
#      run: echo $GITHUB_SHA
    - name: Replace image
      run: |
        ls -lah
        pwd
        new_ver=${{ steps.tagging-strategy.outputs.tags }}
        echo $new_var
        cd argo
        ls -lah
        sed -i -e "s/diegotc\/guestbook:.*/diegotc\/guestbook:$new_ver/g" deployment.yaml
#    - name: Commit & Push changes
#      uses: actions-js/push@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}